// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UpdateComment struct {
	Content *string `json:"content,omitempty"`
}

type UpdateMessage struct {
	Content *string `json:"content,omitempty"`
}

type UpdatePost struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type UpdateUser struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}
