fragment msg on Message {
  id content userId chatId
}

fragment pst on Post {
  id title content userId
}

fragment cmt on Comment {
  id content userId postId
}

fragment usr on User {
  id name email
}

mutation putEverything {
  createUser (input: {name: "Nacho" email: "nacho@mail.com"}) {
    ...usr
  }
  createPost (input: {title: "Post de Nacho" content: "Content del post de Nacho." userId: "6"}) {
    ...pst
  }
  createComment (input: {content: "Nacho's comment" userId: "6", postId: "16"}) {
    ...cmt
  }
  createMessage (input: {content: "Nacho's message" userId: "6" chatId: "2"}) {
    ...msg
  }
  createChat (input: {participants: ["1","2","6"]}) {
    id
  }
}

query getByThings {
  userByEmail (email: "nacho@mail.com") {
    ...usr
  }
  postsByUser (userId: "6") {
    ...pst
  }
  commentsByUser (userId: "6") {
    ...cmt
  }
  commentsByPost (postId: "2") {
    ...cmt
  }
  messagesByUser (userId: "2") {
    ...msg
  }
  messagesByChat (chatId : "2") {
    ...msg
  }
  messagesByChatAndUser (chatId: "2", userId: "2") {
    ...msg
  }
}

query getEverything {
  chats {
    id
  }
  chat (id: "2") {
    id
    messages {
      ...msg
    }
    participants {
      ...usr
    }
  }
  users {
    ...usr
  }
  user (id: "1") {
    id email posts {
      ...pst	
    }
    messages {
      ...msg
    }
    comments {
      ...cmt
    }
    chats {
      id participants {
        ...usr
      }
      messages {
        ...msg
      }
    }
  }
  posts {
    id userId
  }
  post (id: "1") {
     ...pst
    comments {
      ...cmt
    }
  }
  comments {
    ...cmt
  }
  comment (id: "1") {
   	...cmt
  }
  messages {
    ...msg
  }
  message (id: "1") {
    ...msg
  }
}